# Generated by Django 6.0.3 on 2026-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=83019244243, max_length=12),
            preserve_default=False,
        ),
    ]
